// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObQ-qiufRRkCXnAafy0FRRqOkBS_saP8',
    appId: '1:270072580616:web:9dd11dba50078398b91fbd',
    messagingSenderId: '270072580616',
    projectId: 'login-108eb',
    authDomain: 'login-108eb.firebaseapp.com',
    storageBucket: 'login-108eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxM4e-b1hLceQcsoQPl6MHBftoNm8Nso',
    appId: '1:270072580616:android:c5ab90407e12cfa2b91fbd',
    messagingSenderId: '270072580616',
    projectId: 'login-108eb',
    storageBucket: 'login-108eb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBObQ-qiufRRkCXnAafy0FRRqOkBS_saP8',
    appId: '1:270072580616:web:1b5fe91876e04733b91fbd',
    messagingSenderId: '270072580616',
    projectId: 'login-108eb',
    authDomain: 'login-108eb.firebaseapp.com',
    storageBucket: 'login-108eb.appspot.com',
  );

}